FROM python:3.6-slim-stretch

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

RUN pip3 install -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app

RUN pip3 install -e .

EXPOSE 5001

WORKDIR /app/edgefl

# Run app.py when the container launches
CMD ["python", "registration.py"]
